# Generated by Django 5.2.5 on 2025-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisanprofile",
            name="service_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLUMBING", "Plumbing"),
                    ("ELECTRICAL", "Electrical"),
                    ("TILING", "Tiling"),
                    ("PAINTING", "Painting"),
                    ("MECHANIC", "Mechanic"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
